apiVersion: v1
kind: ConfigMap
metadata:
  name:  pp-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: placement-policy-plugins-scheduler
      plugins:
        preScore:
          enabled:
          - name: placementpolicy
        score:
          enabled:
          - name: placementpolicy
        preFilter:
          enabled:
          - name: placementpolicy
        filter:
          enabled:
          - name: placementpolicy
