// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PlacementPolicyListerExpansion allows custom methods to be added to
// PlacementPolicyLister.
type PlacementPolicyListerExpansion interface{}

// PlacementPolicyNamespaceListerExpansion allows custom methods to be added to
// PlacementPolicyNamespaceLister.
type PlacementPolicyNamespaceListerExpansion interface{}
