// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/Azure/placement-policy-scheduler-plugins/apis/v1alpha1"
	"github.com/Azure/placement-policy-scheduler-plugins/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type PlacementpolicyV1alpha1Interface interface {
	RESTClient() rest.Interface
	PlacementPoliciesGetter
}

// PlacementpolicyV1alpha1Client is used to interact with features provided by the placement-policy.scheduling.x-k8s.io group.
type PlacementpolicyV1alpha1Client struct {
	restClient rest.Interface
}

func (c *PlacementpolicyV1alpha1Client) PlacementPolicies(namespace string) PlacementPolicyInterface {
	return newPlacementPolicies(c, namespace)
}

// NewForConfig creates a new PlacementpolicyV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*PlacementpolicyV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &PlacementpolicyV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new PlacementpolicyV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *PlacementpolicyV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new PlacementpolicyV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *PlacementpolicyV1alpha1Client {
	return &PlacementpolicyV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *PlacementpolicyV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
