# permissions for end users to edit placementpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placementpolicy-editor-role
rules:
- apiGroups:
  - placement-policy.scheduling.x-k8s.io
  resources:
  - placementpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - placement-policy.scheduling.x-k8s.io
  resources:
  - placementpolicies/status
  verbs:
  - get
