# permissions for end users to view placementpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placementpolicy-viewer-role
rules:
- apiGroups:
  - placement-policy.scheduling.x-k8s.io
  resources:
  - placementpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - placement-policy.scheduling.x-k8s.io
  resources:
  - placementpolicies/status
  verbs:
  - get
