apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: placement-policy-plugin
    plugins:
      score:
        enabled:
          - name: PlacementPolicyPlugin
        disabled:
          - name: "*"
    pluginConfig:
      - name: PlacementPolicyPlugin
        args:
