apiVersion: placement-policy.scheduling.x-k8s.io/v1alpha1
kind: PlacementPolicy
metadata:
  name: strict-mustnot
spec:
  weight: 100
  enforcementMode: Strict
  podSelector:
    matchLabels:
      app: nginx
  nodeSelector:
    matchLabels:
      node: want
  policy:
    action: MustNot
    targetSize: 40%
