// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Azure/placement-policy-scheduler-plugins/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePlacementPolicies implements PlacementPolicyInterface
type FakePlacementPolicies struct {
	Fake *FakePlacementpolicyV1alpha1
	ns   string
}

var placementpoliciesResource = schema.GroupVersionResource{Group: "placement-policy.scheduling.x-k8s.io", Version: "v1alpha1", Resource: "placementpolicies"}

var placementpoliciesKind = schema.GroupVersionKind{Group: "placement-policy.scheduling.x-k8s.io", Version: "v1alpha1", Kind: "PlacementPolicy"}

// Get takes name of the placementPolicy, and returns the corresponding placementPolicy object, and an error if there is any.
func (c *FakePlacementPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PlacementPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(placementpoliciesResource, c.ns, name), &v1alpha1.PlacementPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlacementPolicy), err
}

// List takes label and field selectors, and returns the list of PlacementPolicies that match those selectors.
func (c *FakePlacementPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PlacementPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(placementpoliciesResource, placementpoliciesKind, c.ns, opts), &v1alpha1.PlacementPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PlacementPolicyList{ListMeta: obj.(*v1alpha1.PlacementPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.PlacementPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested placementPolicies.
func (c *FakePlacementPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(placementpoliciesResource, c.ns, opts))

}

// Create takes the representation of a placementPolicy and creates it.  Returns the server's representation of the placementPolicy, and an error, if there is any.
func (c *FakePlacementPolicies) Create(ctx context.Context, placementPolicy *v1alpha1.PlacementPolicy, opts v1.CreateOptions) (result *v1alpha1.PlacementPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(placementpoliciesResource, c.ns, placementPolicy), &v1alpha1.PlacementPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlacementPolicy), err
}

// Update takes the representation of a placementPolicy and updates it. Returns the server's representation of the placementPolicy, and an error, if there is any.
func (c *FakePlacementPolicies) Update(ctx context.Context, placementPolicy *v1alpha1.PlacementPolicy, opts v1.UpdateOptions) (result *v1alpha1.PlacementPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(placementpoliciesResource, c.ns, placementPolicy), &v1alpha1.PlacementPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlacementPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePlacementPolicies) UpdateStatus(ctx context.Context, placementPolicy *v1alpha1.PlacementPolicy, opts v1.UpdateOptions) (*v1alpha1.PlacementPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(placementpoliciesResource, "status", c.ns, placementPolicy), &v1alpha1.PlacementPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlacementPolicy), err
}

// Delete takes name of the placementPolicy and deletes it. Returns an error if one occurs.
func (c *FakePlacementPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(placementpoliciesResource, c.ns, name), &v1alpha1.PlacementPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePlacementPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(placementpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PlacementPolicyList{})
	return err
}

// Patch applies the patch and returns the patched placementPolicy.
func (c *FakePlacementPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PlacementPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(placementpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.PlacementPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PlacementPolicy), err
}
