// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/Azure/placement-policy-scheduler-plugins/pkg/client/clientset/versioned/typed/apis/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePlacementpolicyV1alpha1 struct {
	*testing.Fake
}

func (c *FakePlacementpolicyV1alpha1) PlacementPolicies(namespace string) v1alpha1.PlacementPolicyInterface {
	return &FakePlacementPolicies{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePlacementpolicyV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
