name: test

on: [pull_request]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: golangci-lint
      run: make lint

  unit-test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run unit tests
      run: make unit-test

  integration-test:
    name: "Integration Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run integration tests
      run: make integration-test
  
  e2e-test:
    name: "E2E Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run e2e test
      run: OUTPUT_TYPE=type=docker make docker-build e2e-test
