// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apisv1alpha1 "github.com/Azure/placement-policy-scheduler-plugins/apis/v1alpha1"
	versioned "github.com/Azure/placement-policy-scheduler-plugins/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/placement-policy-scheduler-plugins/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/Azure/placement-policy-scheduler-plugins/pkg/client/listers/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PlacementPolicyInformer provides access to a shared informer and lister for
// PlacementPolicies.
type PlacementPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PlacementPolicyLister
}

type placementPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPlacementPolicyInformer constructs a new informer for PlacementPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPlacementPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPlacementPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPlacementPolicyInformer constructs a new informer for PlacementPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPlacementPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PlacementpolicyV1alpha1().PlacementPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PlacementpolicyV1alpha1().PlacementPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1alpha1.PlacementPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *placementPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPlacementPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *placementPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1alpha1.PlacementPolicy{}, f.defaultInformer)
}

func (f *placementPolicyInformer) Lister() v1alpha1.PlacementPolicyLister {
	return v1alpha1.NewPlacementPolicyLister(f.Informer().GetIndexer())
}
